version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/start"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/complete"
    schedule:
      interval: "weekly"
